### ISSUE TITLE
Maml is used instead of Reptile?

### ISSUE THREAD

**Issue by serre20** [zhyliu00/TPB#2]
It is declared that Reptile is used as the meta learning method in your paper, but it seems that Maml is used in your code instead of Reptile.

**Comment by zhyliu00** [comment]
Actually, it is just a variable name. We here store the multi-step gradient from the support task as shown in https://github.com/zhyliu00/TPB/blob/5ffd2efbf6786a2252b344de81819570fc5159a9/model/Meta_Models/rep_model_final.py#L234

Moreover, the algorithm here maybe a little different from the origin Reptile algorithm. We still take support set and query set here and the performance is good.

**Comment by serre20** [comment]
OK, thank you for your reply!
