### ISSUE TITLE
pattern文件夹

### ISSUE THREAD

**Issue by ZhangYuan1998** [zhyliu00/TPB#3]
您好！在此向您请教，pattern文件夹中的文件是怎么得到的。
祝您一切顺利！

**Comment by zhyliu00** [comment]
你好，可以使用pretrain.py预训练，再使用patch_devide.py得到patch_embeddings，最后使用pattern_clustering.py聚类得到pattern里面的文件

**Comment by ZhangYuan1998** [comment]
好的非常感谢您回复！
