### ISSUE TITLE
Question about clustering parameter K

### ISSUE THREAD

**Issue by packer-c** [zhyliu00/TPB#5]
Thanks for your nice work and code.

I would like to know about the K value. Is your final choose K = 10? For all datasets. 
Sorry I didn't find it in your paper, but I saw Figure 5, I guess K =10. 

Looking forward to your reply.

**Comment by zhyliu00** [comment]
In METR-LA, K=5
In other datasets K=10.

**Comment by packer-c** [comment]
> In METR-LA, K=5 In other datasets K=10.

Thank you for your reply!
And, may I know how to draw a visualization of Fig.5 (e)~(j) in your paper? I mean in which and where .py file should I add the visualization code.

**Comment by zhyliu00** [comment]
The plot code is not included in the repo, but it is a simple TSNE visualization. We directly `sklearn.manifold.TSNE` package to fit the embedding of the source traffic, and use `matplotlib` to plot the visualization.

**Comment by packer-c** [comment]
Got it, Thanks a lot!
