### ISSUE TITLE
dataset_expand如何得到？

### ISSUE THREAD

**Issue by bu2chen** [zhyliu00/TPB#6]
您好！我想向您请教一下，如果我想复现其他数据集，比如pems04，我应该如何得到dataset_expand呢，应该如何数据处理？

**Comment by zhyliu00** [comment]
dataset_expand是原数据集做了简单的线性插值处理后的数据集。
我们这样做，是想将chengdu和shenzhen的数据集的时间粒度从10min变成5min，从而与pems-bay和metr-la的时间粒度对齐，进而对其positional embedding。
